services:
  acme_bundle_testbundle_service_articlerandomizer:
    class: Acme\Bundle\TestBundle\Service\ArticleRandomizer

  Acme\Bundle\TestBundle\Service\ArticleRandomizer:
    alias: acme_bundle_testbundle_service_articlerandomizer

  Acme\Bundle\TestBundle\Repository\:
    resource: '../../Repository/*Repository.php'
    autoconfigure: true
    autowire: true
    tags: ['doctrine.repository_service']
