services:
  acme_testbundle_service_articlerandomizer:
    class: Acme\TestBundle\Service\ArticleRandomizer

  Acme\TestBundle\Service\ArticleRandomizer:
    alias: acme_testbundle_service_articlerandomizer

